export const SET_USER = "SET_USER";
export const SET_NAV = "SET_NAV";
export const SET_DIM_BACKGROUND = "SET_DIM_BACKGROUND";
export const DISMISS_DIM_BACKGROUND = "DISMISS_DIM_BACKGROUND";
export const SHOW_ACTION_SHEET = "SHOW_ACTION_SHEET";
export const DISMISS_ACTION_SHEET = "DISMISS_ACTION_SHEET";
